<?php
$countries = [
    ['code' => 'AF', 'name' => 'Afghanistan', 'dial_code' => '+93'],
    ['code' => 'AL', 'name' => 'Albanie', 'dial_code' => '+355'],
    ['code' => 'DZ', 'name' => 'Algérie', 'dial_code' => '+213'],
    ['code' => 'AD', 'name' => 'Andorre', 'dial_code' => '+376'],
    ['code' => 'AO', 'name' => 'Angola', 'dial_code' => '+244'],
    ['code' => 'AG', 'name' => 'Antigua-et-Barbuda', 'dial_code' => '+1'],
    ['code' => 'AR', 'name' => 'Argentine', 'dial_code' => '+54'],
    ['code' => 'AM', 'name' => 'Arménie', 'dial_code' => '+374'],
    ['code' => 'AU', 'name' => 'Australie', 'dial_code' => '+61'],
    ['code' => 'AT', 'name' => 'Autriche', 'dial_code' => '+43'],
    ['code' => 'AZ', 'name' => 'Azerbaïdjan', 'dial_code' => '+994'],
    ['code' => 'BS', 'name' => 'Bahamas', 'dial_code' => '+1'],
    ['code' => 'BH', 'name' => 'Bahreïn', 'dial_code' => '+973'],
    ['code' => 'BD', 'name' => 'Bangladesh', 'dial_code' => '+880'],
    ['code' => 'BB', 'name' => 'Barbade', 'dial_code' => '+1'],
    ['code' => 'BY', 'name' => 'Biélorussie', 'dial_code' => '+375'],
    ['code' => 'BE', 'name' => 'Belgique', 'dial_code' => '+32'],
    ['code' => 'BZ', 'name' => 'Belize', 'dial_code' => '+501'],
    ['code' => 'BJ', 'name' => 'Bénin', 'dial_code' => '+229'],
    ['code' => 'BT', 'name' => 'Bhoutan', 'dial_code' => '+975'],
    ['code' => 'BO', 'name' => 'Bolivie', 'dial_code' => '+591'],
    ['code' => 'BA', 'name' => 'Bosnie-Herzégovine', 'dial_code' => '+387'],
    ['code' => 'BW', 'name' => 'Botswana', 'dial_code' => '+267'],
    ['code' => 'BR', 'name' => 'Brésil', 'dial_code' => '+55'],
    ['code' => 'BN', 'name' => 'Brunei', 'dial_code' => '+673'],
    ['code' => 'BG', 'name' => 'Bulgarie', 'dial_code' => '+359'],
    ['code' => 'BF', 'name' => 'Burkina Faso', 'dial_code' => '+226'],
    ['code' => 'BI', 'name' => 'Burundi', 'dial_code' => '+257'],
    ['code' => 'KH', 'name' => 'Cambodge', 'dial_code' => '+855'],
    ['code' => 'CM', 'name' => 'Cameroun', 'dial_code' => '+237'],
    ['code' => 'CA', 'name' => 'Canada', 'dial_code' => '+1'],
    ['code' => 'CV', 'name' => 'Cap-Vert', 'dial_code' => '+238'],
    ['code' => 'CF', 'name' => 'République centrafricaine', 'dial_code' => '+236'],
    ['code' => 'TD', 'name' => 'Tchad', 'dial_code' => '+235'],
    ['code' => 'CL', 'name' => 'Chili', 'dial_code' => '+56'],
    ['code' => 'CN', 'name' => 'Chine', 'dial_code' => '+86'],
    ['code' => 'CO', 'name' => 'Colombie', 'dial_code' => '+57'],
    ['code' => 'KM', 'name' => 'Comores', 'dial_code' => '+269'],
    ['code' => 'CG', 'name' => 'Congo', 'dial_code' => '+242'],
    ['code' => 'CR', 'name' => 'Costa Rica', 'dial_code' => '+506'],
    ['code' => 'HR', 'name' => 'Croatie', 'dial_code' => '+385'],
    ['code' => 'CU', 'name' => 'Cuba', 'dial_code' => '+53'],
    ['code' => 'CY', 'name' => 'Chypre', 'dial_code' => '+357'],
    ['code' => 'CZ', 'name' => 'République tchèque', 'dial_code' => '+420'],
    ['code' => 'DK', 'name' => 'Danemark', 'dial_code' => '+45'],
    ['code' => 'DJ', 'name' => 'Djibouti', 'dial_code' => '+253'],
    ['code' => 'DM', 'name' => 'Dominique', 'dial_code' => '+1'],
    ['code' => 'DO', 'name' => 'République dominicaine', 'dial_code' => '+1'],
    ['code' => 'EC', 'name' => 'Équateur', 'dial_code' => '+593'],
    ['code' => 'EG', 'name' => 'Égypte', 'dial_code' => '+20'],
    ['code' => 'SV', 'name' => 'El Salvador', 'dial_code' => '+503'],
    ['code' => 'GQ', 'name' => 'Guinée équatoriale', 'dial_code' => '+240'],
    ['code' => 'ER', 'name' => 'Érythrée', 'dial_code' => '+291'],
    ['code' => 'EE', 'name' => 'Estonie', 'dial_code' => '+372'],
    ['code' => 'ET', 'name' => 'Éthiopie', 'dial_code' => '+251'],
    ['code' => 'FJ', 'name' => 'Fidji', 'dial_code' => '+679'],
    ['code' => 'FI', 'name' => 'Finlande', 'dial_code' => '+358'],
    ['code' => 'FR', 'name' => 'France', 'dial_code' => '+33'],
    ['code' => 'GA', 'name' => 'Gabon', 'dial_code' => '+241'],
    ['code' => 'GM', 'name' => 'Gambie', 'dial_code' => '+220'],
    ['code' => 'GE', 'name' => 'Géorgie', 'dial_code' => '+995'],
    ['code' => 'DE', 'name' => 'Allemagne', 'dial_code' => '+49'],
    ['code' => 'GH', 'name' => 'Ghana', 'dial_code' => '+233'],
    ['code' => 'GR', 'name' => 'Grèce', 'dial_code' => '+30'],
    ['code' => 'GD', 'name' => 'Grenade', 'dial_code' => '+1'],
    ['code' => 'GT', 'name' => 'Guatemala', 'dial_code' => '+502'],
    ['code' => 'GN', 'name' => 'Guinée', 'dial_code' => '+224'],
    ['code' => 'GW', 'name' => 'Guinée-Bissau', 'dial_code' => '+245'],
    ['code' => 'GY', 'name' => 'Guyana', 'dial_code' => '+592'],
    ['code' => 'HT', 'name' => 'Haïti', 'dial_code' => '+509'],
    ['code' => 'HN', 'name' => 'Honduras', 'dial_code' => '+504'],
    ['code' => 'HK', 'name' => 'Hong Kong', 'dial_code' => '+852'],
    ['code' => 'HU', 'name' => 'Hongrie', 'dial_code' => '+36'],
    ['code' => 'IS', 'name' => 'Islande', 'dial_code' => '+354'],
    ['code' => 'IN', 'name' => 'Inde', 'dial_code' => '+91'],
    ['code' => 'ID', 'name' => 'Indonésie', 'dial_code' => '+62'],
    ['code' => 'IR', 'name' => 'Iran', 'dial_code' => '+98'],
    ['code' => 'IQ', 'name' => 'Irak', 'dial_code' => '+964'],
    ['code' => 'IE', 'name' => 'Irlande', 'dial_code' => '+353'],
    ['code' => 'IL', 'name' => 'Israël', 'dial_code' => '+972'],
    ['code' => 'IT', 'name' => 'Italie', 'dial_code' => '+39'],
    ['code' => 'JM', 'name' => 'Jamaïque', 'dial_code' => '+1'],
    ['code' => 'JP', 'name' => 'Japon', 'dial_code' => '+81'],
    ['code' => 'JO', 'name' => 'Jordanie', 'dial_code' => '+962'],
    ['code' => 'KZ', 'name' => 'Kazakhstan', 'dial_code' => '+7'],
    ['code' => 'KE', 'name' => 'Kenya', 'dial_code' => '+254'],
    ['code' => 'KI', 'name' => 'Kiribati', 'dial_code' => '+686'],
    ['code' => 'KP', 'name' => 'Corée du Nord', 'dial_code' => '+850'],
    ['code' => 'KR', 'name' => 'Corée du Sud', 'dial_code' => '+82'],
    ['code' => 'KW', 'name' => 'Koweït', 'dial_code' => '+965'],
    ['code' => 'KG', 'name' => 'Kirghizistan', 'dial_code' => '+996'],
    ['code' => 'LA', 'name' => 'Laos', 'dial_code' => '+856'],
    ['code' => 'LV', 'name' => 'Lettonie', 'dial_code' => '+371'],
    ['code' => 'LB', 'name' => 'Liban', 'dial_code' => '+961'],
    ['code' => 'LS', 'name' => 'Lesotho', 'dial_code' => '+266'],
    ['code' => 'LR', 'name' => 'Libéria', 'dial_code' => '+231'],
    ['code' => 'LY', 'name' => 'Libye', 'dial_code' => '+218'],
    ['code' => 'LI', 'name' => 'Liechtenstein', 'dial_code' => '+423'],
    ['code' => 'LT', 'name' => 'Lituanie', 'dial_code' => '+370'],
    ['code' => 'LU', 'name' => 'Luxembourg', 'dial_code' => '+352'],
    ['code' => 'MO', 'name' => 'Macao', 'dial_code' => '+853'],
    ['code' => 'MK', 'name' => 'Macédoine du Nord', 'dial_code' => '+389'],
    ['code' => 'MG', 'name' => 'Madagascar', 'dial_code' => '+261'],
    ['code' => 'MW', 'name' => 'Malawi', 'dial_code' => '+265'],
    ['code' => 'MY', 'name' => 'Malaisie', 'dial_code' => '+60'],
    ['code' => 'MV', 'name' => 'Maldives', 'dial_code' => '+960'],
    ['code' => 'ML', 'name' => 'Mali', 'dial_code' => '+223'],
    ['code' => 'MT', 'name' => 'Malte', 'dial_code' => '+356'],
    ['code' => 'MH', 'name' => 'Îles Marshall', 'dial_code' => '+692'],
    ['code' => 'MR', 'name' => 'Mauritanie', 'dial_code' => '+222'],
    ['code' => 'MU', 'name' => 'Maurice', 'dial_code' => '+230'],
    ['code' => 'MX', 'name' => 'Mexique', 'dial_code' => '+52'],
    ['code' => 'FM', 'name' => 'Micronésie', 'dial_code' => '+691'],
    ['code' => 'MD', 'name' => 'Moldavie', 'dial_code' => '+373'],
    ['code' => 'MC', 'name' => 'Monaco', 'dial_code' => '+377'],
    ['code' => 'MN', 'name' => 'Mongolie', 'dial_code' => '+976'],
    ['code' => 'ME', 'name' => 'Monténégro', 'dial_code' => '+382'],
    ['code' => 'MA', 'name' => 'Maroc', 'dial_code' => '+212'],
    ['code' => 'MZ', 'name' => 'Mozambique', 'dial_code' => '+258'],
    ['code' => 'MM', 'name' => 'Myanmar', 'dial_code' => '+95'],
    ['code' => 'NA', 'name' => 'Namibie', 'dial_code' => '+264'],
    ['code' => 'NR', 'name' => 'Nauru', 'dial_code' => '+674'],
    ['code' => 'NP', 'name' => 'Népal', 'dial_code' => '+977'],
    ['code' => 'NL', 'name' => 'Pays-Bas', 'dial_code' => '+31'],
    ['code' => 'NZ', 'name' => 'Nouvelle-Zélande', 'dial_code' => '+64'],
    ['code' => 'NI', 'name' => 'Nicaragua', 'dial_code' => '+505'],
    ['code' => 'NE', 'name' => 'Niger', 'dial_code' => '+227'],
    ['code' => 'NG', 'name' => 'Nigeria', 'dial_code' => '+234'],
    ['code' => 'NO', 'name' => 'Norvège', 'dial_code' => '+47'],
    ['code' => 'OM', 'name' => 'Oman', 'dial_code' => '+968'],
    ['code' => 'PK', 'name' => 'Pakistan', 'dial_code' => '+92'],
    ['code' => 'PW', 'name' => 'Palaos', 'dial_code' => '+680'],
    ['code' => 'PS', 'name' => 'Palestine', 'dial_code' => '+970'],
    ['code' => 'PA', 'name' => 'Panama', 'dial_code' => '+507'],
    ['code' => 'PG', 'name' => 'Papouasie-Nouvelle-Guinée', 'dial_code' => '+675'],
    ['code' => 'PY', 'name' => 'Paraguay', 'dial_code' => '+595'],
    ['code' => 'PE', 'name' => 'Pérou', 'dial_code' => '+51'],
    ['code' => 'PH', 'name' => 'Philippines', 'dial_code' => '+63'],
    ['code' => 'PL', 'name' => 'Pologne', 'dial_code' => '+48'],
    ['code' => 'PT', 'name' => 'Portugal', 'dial_code' => '+351'],
    ['code' => 'QA', 'name' => 'Qatar', 'dial_code' => '+974'],
    ['code' => 'RO', 'name' => 'Roumanie', 'dial_code' => '+40'],
    ['code' => 'RU', 'name' => 'Russie', 'dial_code' => '+7'],
    ['code' => 'RW', 'name' => 'Rwanda', 'dial_code' => '+250'],
    ['code' => 'KN', 'name' => 'Saint-Kitts-et-Nevis', 'dial_code' => '+1'],
    ['code' => 'LC', 'name' => 'Sainte-Lucie', 'dial_code' => '+1'],
    ['code' => 'VC', 'name' => 'Saint-Vincent-et-les-Grenadines', 'dial_code' => '+1'],
    ['code' => 'WS', 'name' => 'Samoa', 'dial_code' => '+685'],
    ['code' => 'SM', 'name' => 'Saint-Marin', 'dial_code' => '+378'],
    ['code' => 'ST', 'name' => 'Sao Tomé-et-Principe', 'dial_code' => '+239'],
    ['code' => 'SA', 'name' => 'Arabie saoudite', 'dial_code' => '+966'],
    ['code' => 'SN', 'name' => 'Sénégal', 'dial_code' => '+221'],
    ['code' => 'RS', 'name' => 'Serbie', 'dial_code' => '+381'],
    ['code' => 'SC', 'name' => 'Seychelles', 'dial_code' => '+248'],
    ['code' => 'SL', 'name' => 'Sierra Leone', 'dial_code' => '+232'],
    ['code' => 'SG', 'name' => 'Singapour', 'dial_code' => '+65'],
    ['code' => 'SK', 'name' => 'Slovaquie', 'dial_code' => '+421'],
    ['code' => 'SI', 'name' => 'Slovénie', 'dial_code' => '+386'],
    ['code' => 'SB', 'name' => 'Îles Salomon', 'dial_code' => '+677'],
    ['code' => 'SO', 'name' => 'Somalie', 'dial_code' => '+252'],
    ['code' => 'ZA', 'name' => 'Afrique du Sud', 'dial_code' => '+27'],
    ['code' => 'SS', 'name' => 'Soudan du Sud', 'dial_code' => '+211'],
    ['code' => 'ES', 'name' => 'Espagne', 'dial_code' => '+34'],
    ['code' => 'LK', 'name' => 'Sri Lanka', 'dial_code' => '+94'],
    ['code' => 'SD', 'name' => 'Soudan', 'dial_code' => '+249'],
    ['code' => 'SR', 'name' => 'Suriname', 'dial_code' => '+597'],
    ['code' => 'SZ', 'name' => 'Eswatini', 'dial_code' => '+268'],
    ['code' => 'SE', 'name' => 'Suède', 'dial_code' => '+46'],
    ['code' => 'CH', 'name' => 'Suisse', 'dial_code' => '+41'],
    ['code' => 'SY', 'name' => 'Syrie', 'dial_code' => '+963'],
    ['code' => 'TW', 'name' => 'Taïwan', 'dial_code' => '+886'],
    ['code' => 'TJ', 'name' => 'Tadjikistan', 'dial_code' => '+992'],
    ['code' => 'TZ', 'name' => 'Tanzanie', 'dial_code' => '+255'],
    ['code' => 'TH', 'name' => 'Thaïlande', 'dial_code' => '+66'],
    ['code' => 'TL', 'name' => 'Timor oriental', 'dial_code' => '+670'],
    ['code' => 'TG', 'name' => 'Togo', 'dial_code' => '+228'],
    ['code' => 'TO', 'name' => 'Tonga', 'dial_code' => '+676'],
    ['code' => 'TT', 'name' => 'Trinité-et-Tobago', 'dial_code' => '+1'],
    ['code' => 'TN', 'name' => 'Tunisie', 'dial_code' => '+216'],
    ['code' => 'TR', 'name' => 'Turquie', 'dial_code' => '+90'],
    ['code' => 'TM', 'name' => 'Turkménistan', 'dial_code' => '+993'],
    ['code' => 'TV', 'name' => 'Tuvalu', 'dial_code' => '+688'],
    ['code' => 'UG', 'name' => 'Ouganda', 'dial_code' => '+256'],
    ['code' => 'UA', 'name' => 'Ukraine', 'dial_code' => '+380'],
    ['code' => 'AE', 'name' => 'Émirats arabes unis', 'dial_code' => '+971'],
    ['code' => 'GB', 'name' => 'Royaume-Uni', 'dial_code' => '+44'],
    ['code' => 'US', 'name' => 'États-Unis', 'dial_code' => '+1'],
    ['code' => 'UY', 'name' => 'Uruguay', 'dial_code' => '+598'],
    ['code' => 'UZ', 'name' => 'Ouzbékistan', 'dial_code' => '+998'],
    ['code' => 'VU', 'name' => 'Vanuatu', 'dial_code' => '+678'],
    ['code' => 'VA', 'name' => 'Vatican', 'dial_code' => '+379'],
    ['code' => 'VE', 'name' => 'Venezuela', 'dial_code' => '+58'],
    ['code' => 'VN', 'name' => 'Vietnam', 'dial_code' => '+84'],
    ['code' => 'YE', 'name' => 'Yémen', 'dial_code' => '+967'],
    ['code' => 'ZM', 'name' => 'Zambie', 'dial_code' => '+260'],
    ['code' => 'ZW', 'name' => 'Zimbabwe', 'dial_code' => '+263']
];

// Trier les pays par nom
usort($countries, function($a, $b) {
    return strcmp($a['name'], $b['name']);
});

// Retourner la liste des pays
return $countries;
?> 