export const countries = [
  { value: 'AF', label: 'Afghanistan' },
  { value: 'ZA', label: 'Afrique du Sud' },
  { value: 'AL', label: 'Albanie' },
  { value: 'DZ', label: 'Algérie' },
  { value: 'DE', label: 'Allemagne' },
  { value: 'AD', label: 'Andorre' },
  { value: 'AO', label: 'Angola' },
  { value: 'AI', label: 'Anguilla' },
  { value: 'AQ', label: 'Antarctique' },
  { value: 'AG', label: 'Antigua-et-Barbuda' },
  { value: 'SA', label: 'Arabie saoudite' },
  { value: 'AR', label: 'Argentine' },
  { value: 'AM', label: 'Arménie' },
  { value: 'AW', label: 'Aruba' },
  { value: 'AU', label: 'Australie' },
  { value: 'AT', label: 'Autriche' },
  { value: 'AZ', label: 'Azerbaïdjan' },
  { value: 'BS', label: 'Bahamas' },
  { value: 'BH', label: 'Bahreïn' },
  { value: 'BD', label: 'Bangladesh' },
  { value: 'BB', label: 'Barbade' },
  { value: 'BY', label: 'Biélorussie' },
  { value: 'BE', label: 'Belgique' },
  { value: 'BZ', label: 'Belize' },
  { value: 'BJ', label: 'Bénin' },
  { value: 'BM', label: 'Bermudes' },
  { value: 'BT', label: 'Bhoutan' },
  { value: 'BO', label: 'Bolivie' },
  { value: 'BA', label: 'Bosnie-Herzégovine' },
  { value: 'BW', label: 'Botswana' },
  { value: 'BR', label: 'Brésil' },
  { value: 'BN', label: 'Brunei' },
  { value: 'BG', label: 'Bulgarie' },
  { value: 'BF', label: 'Burkina Faso' },
  { value: 'BI', label: 'Burundi' },
  { value: 'KH', label: 'Cambodge' },
  { value: 'CM', label: 'Cameroun' },
  { value: 'CA', label: 'Canada' },
  { value: 'CV', label: 'Cap-Vert' },
  { value: 'CL', label: 'Chili' },
  { value: 'CN', label: 'Chine' },
  { value: 'CY', label: 'Chypre' },
  { value: 'CO', label: 'Colombie' },
  { value: 'KM', label: 'Comores' },
  { value: 'CG', label: 'Congo-Brazzaville' },
  { value: 'CD', label: 'Congo-Kinshasa' },
  { value: 'KR', label: 'Corée du Sud' },
  { value: 'KP', label: 'Corée du Nord' },
  { value: 'CR', label: 'Costa Rica' },
  { value: 'CI', label: 'Côte d\'Ivoire' },
  { value: 'HR', label: 'Croatie' },
  { value: 'CU', label: 'Cuba' },
  { value: 'DK', label: 'Danemark' },
  { value: 'DJ', label: 'Djibouti' },
  { value: 'DM', label: 'Dominique' },
  { value: 'EG', label: 'Égypte' },
  { value: 'AE', label: 'Émirats arabes unis' },
  { value: 'EC', label: 'Équateur' },
  { value: 'ER', label: 'Érythrée' },
  { value: 'ES', label: 'Espagne' },
  { value: 'EE', label: 'Estonie' },
  { value: 'SZ', label: 'Eswatini' },
  { value: 'US', label: 'États-Unis' },
  { value: 'ET', label: 'Éthiopie' },
  { value: 'FJ', label: 'Fidji' },
  { value: 'FI', label: 'Finlande' },
  { value: 'FR', label: 'France' },
  { value: 'GA', label: 'Gabon' },
  { value: 'GM', label: 'Gambie' },
  { value: 'GE', label: 'Géorgie' },
  { value: 'GH', label: 'Ghana' },
  { value: 'GR', label: 'Grèce' },
  { value: 'GD', label: 'Grenade' },
  { value: 'GT', label: 'Guatemala' },
  { value: 'GN', label: 'Guinée' },
  { value: 'GQ', label: 'Guinée équatoriale' },
  { value: 'GW', label: 'Guinée-Bissau' },
  { value: 'GY', label: 'Guyana' },
  { value: 'HT', label: 'Haïti' },
  { value: 'HN', label: 'Honduras' },
  { value: 'HU', label: 'Hongrie' },
  { value: 'IN', label: 'Inde' },
  { value: 'ID', label: 'Indonésie' },
  { value: 'IQ', label: 'Irak' },
  { value: 'IR', label: 'Iran' },
  { value: 'IE', label: 'Irlande' },
  { value: 'IS', label: 'Islande' },
  { value: 'IT', label: 'Italie' },
  { value: 'JM', label: 'Jamaïque' },
  { value: 'JP', label: 'Japon' },
  { value: 'JO', label: 'Jordanie' },
  { value: 'KZ', label: 'Kazakhstan' },
  { value: 'KE', label: 'Kenya' },
  { value: 'KG', label: 'Kirghizistan' },
  { value: 'KI', label: 'Kiribati' },
  { value: 'KW', label: 'Koweït' },
  { value: 'LA', label: 'Laos' },
  { value: 'LS', label: 'Lesotho' },
  { value: 'LV', label: 'Lettonie' },
  { value: 'LB', label: 'Liban' },
  { value: 'LR', label: 'Libéria' },
  { value: 'LY', label: 'Libye' },
  { value: 'LI', label: 'Liechtenstein' },
  { value: 'LT', label: 'Lituanie' },
  { value: 'LU', label: 'Luxembourg' },
  { value: 'MK', label: 'Macédoine du Nord' },
  { value: 'MG', label: 'Madagascar' },
  { value: 'MY', label: 'Malaisie' },
  { value: 'MW', label: 'Malawi' },
  { value: 'MV', label: 'Maldives' },
  { value: 'ML', label: 'Mali' },
  { value: 'MT', label: 'Malte' },
  { value: 'MA', label: 'Maroc' },
  { value: 'MU', label: 'Maurice' },
  { value: 'MR', label: 'Mauritanie' },
  { value: 'MX', label: 'Mexique' },
  { value: 'MD', label: 'Moldavie' },
  { value: 'MC', label: 'Monaco' },
  { value: 'MN', label: 'Mongolie' },
  { value: 'ME', label: 'Monténégro' },
  { value: 'MZ', label: 'Mozambique' },
  { value: 'NA', label: 'Namibie' },
  { value: 'NP', label: 'Népal' },
  { value: 'NI', label: 'Nicaragua' },
  { value: 'NE', label: 'Niger' },
  { value: 'NG', label: 'Nigéria' },
  { value: 'NO', label: 'Norvège' },
  { value: 'NZ', label: 'Nouvelle-Zélande' },
  { value: 'OM', label: 'Oman' },
  { value: 'UG', label: 'Ouganda' },
  { value: 'UZ', label: 'Ouzbékistan' },
  { value: 'PK', label: 'Pakistan' },
  { value: 'PA', label: 'Panama' },
  { value: 'PG', label: 'Papouasie-Nouvelle-Guinée' },
  { value: 'PY', label: 'Paraguay' },
  { value: 'NL', label: 'Pays-Bas' },
  { value: 'PE', label: 'Pérou' },
  { value: 'PH', label: 'Philippines' },
  { value: 'PL', label: 'Pologne' },
  { value: 'PT', label: 'Portugal' },
  { value: 'QA', label: 'Qatar' },
  { value: 'RO', label: 'Roumanie' },
  { value: 'GB', label: 'Royaume-Uni' },
  { value: 'RU', label: 'Russie' },
  { value: 'RW', label: 'Rwanda' },
  { value: 'LC', label: 'Sainte-Lucie' },
  { value: 'SM', label: 'Saint-Marin' },
  { value: 'ST', label: 'Sao Tomé-et-Principe' },
  { value: 'SN', label: 'Sénégal' },
  { value: 'RS', label: 'Serbie' },
  { value: 'SC', label: 'Seychelles' },
  { value: 'SL', label: 'Sierra Leone' },
  { value: 'SG', label: 'Singapour' },
  { value: 'SK', label: 'Slovaquie' },
  { value: 'SI', label: 'Slovénie' },
  { value: 'SO', label: 'Somalie' },
  { value: 'SD', label: 'Soudan' },
  { value: 'SS', label: 'Soudan du Sud' },
  { value: 'SE', label: 'Suède' },
  { value: 'CH', label: 'Suisse' },
  { value: 'SR', label: 'Suriname' },
  { value: 'SY', label: 'Syrie' },
  { value: 'TJ', label: 'Tadjikistan' },
  { value: 'TZ', label: 'Tanzanie' },
  { value: 'TD', label: 'Tchad' },
  { value: 'CZ', label: 'Tchéquie' },
  { value: 'TH', label: 'Thaïlande' },
  { value: 'TL', label: 'Timor oriental' },
  { value: 'TG', label: 'Togo' },
  { value: 'TO', label: 'Tonga' },
  { value: 'TT', label: 'Trinité-et-Tobago' },
  { value: 'TN', label: 'Tunisie' },
  { value: 'TM', label: 'Turkménistan' },
  { value: 'TR', label: 'Turquie' },
  { value: 'UA', label: 'Ukraine' },
  { value: 'UY', label: 'Uruguay' },
  { value: 'VU', label: 'Vanuatu' },
  { value: 'VE', label: 'Venezuela' },
  { value: 'VN', label: 'Viêt Nam' },
  { value: 'YE', label: 'Yémen' },
  { value: 'ZM', label: 'Zambie' },
  { value: 'ZW', label: 'Zimbabwe' },
].sort((a, b) => a.label.localeCompare(b.label, 'fr'));

