const countryMapping = {
  'Afghanistan': 'AF',
  'Afrique du Sud': 'ZA',
  'Albanie': 'AL',
  'Algérie': 'DZ',
  'Allemagne': 'DE',
  'Andorre': 'AD',
  'Angola': 'AO',
  'Anguilla': 'AI',
  'Antarctique': 'AQ',
  'Antigua-et-Barbuda': 'AG',
  'Arabie saoudite': 'SA',
  'Argentine': 'AR',
  'Arménie': 'AM',
  'Aruba': 'AW',
  'Australie': 'AU',
  'Autriche': 'AT',
  'Azerbaïdjan': 'AZ',
  'Bahamas': 'BS',
  'Bahreïn': 'BH',
  'Bangladesh': 'BD',
  'Barbade': 'BB',
  'Biélorussie': 'BY',
  'Belgique': 'BE',
  'Belize': 'BZ',
  'Bénin': 'BJ',
  'Bermudes': 'BM',
  'Bhoutan': 'BT',
  'Bolivie': 'BO',
  'Bosnie-Herzégovine': 'BA',
  'Botswana': 'BW',
  'Brésil': 'BR',
  'Brunei': 'BN',
  'Bulgarie': 'BG',
  'Burkina Faso': 'BF',
  'Burundi': 'BI',
  'Cambodge': 'KH',
  'Cameroun': 'CM',
  'Canada': 'CA',
  'Cap-Vert': 'CV',
  'Chili': 'CL',
  'Chine': 'CN',
  'Chypre': 'CY',
  'Colombie': 'CO',
  'Comores': 'KM',
  'Congo-Brazzaville': 'CG',
  'Congo-Kinshasa': 'CD',
  'Corée du Sud': 'KR',
  'Corée du Nord': 'KP',
  'Costa Rica': 'CR',
  "Côte d'Ivoire": 'CI',
  'Croatie': 'HR',
  'Cuba': 'CU',
  'Danemark': 'DK',
  'Djibouti': 'DJ',
  'Dominique': 'DM',
  'Égypte': 'EG',
  'Émirats arabes unis': 'AE',
  'Équateur': 'EC',
  'Érythrée': 'ER',
  'Espagne': 'ES',
  'Estonie': 'EE',
  'Eswatini': 'SZ',
  'États-Unis': 'US',
  'Éthiopie': 'ET',
  'Fidji': 'FJ',
  'Finlande': 'FI',
  'France': 'FR',
  'Gabon': 'GA',
  'Gambie': 'GM',
  'Géorgie': 'GE',
  'Ghana': 'GH',
  'Grèce': 'GR',
  'Grenade': 'GD',
  'Guatemala': 'GT',
  'Guinée': 'GN',
  'Guinée équatoriale': 'GQ',
  'Guinée-Bissau': 'GW',
  'Guyana': 'GY',
  'Haïti': 'HT',
  'Honduras': 'HN',
  'Hongrie': 'HU',
  'Inde': 'IN',
  'Indonésie': 'ID',
  'Irak': 'IQ',
  'Iran': 'IR',
  'Irlande': 'IE',
  'Islande': 'IS',
  'Italie': 'IT',
  'Jamaïque': 'JM',
  'Japon': 'JP',
  'Jordanie': 'JO',
  'Kazakhstan': 'KZ',
  'Kenya': 'KE',
  'Kirghizistan': 'KG',
  'Kiribati': 'KI',
  'Koweït': 'KW',
  'Laos': 'LA',
  'Lesotho': 'LS',
  'Lettonie': 'LV',
  'Liban': 'LB',
  'Libéria': 'LR',
  'Libye': 'LY',
  'Liechtenstein': 'LI',
  'Lituanie': 'LT',
  'Luxembourg': 'LU',
  'Macédoine du Nord': 'MK',
  'Madagascar': 'MG',
  'Malaisie': 'MY',
  'Malawi': 'MW',
  'Maldives': 'MV',
  'Mali': 'ML',
  'Malte': 'MT',
  'Maroc': 'MA',
  'Maurice': 'MU',
  'Mauritanie': 'MR',
  'Mexique': 'MX',
  'Moldavie': 'MD',
  'Monaco': 'MC',
  'Mongolie': 'MN',
  'Monténégro': 'ME',
  'Mozambique': 'MZ',
  'Namibie': 'NA',
  'Népal': 'NP',
  'Nicaragua': 'NI',
  'Niger': 'NE',
  'Nigéria': 'NG',
  'Norvège': 'NO',
  'Nouvelle-Zélande': 'NZ',
  'Oman': 'OM',
  'Ouganda': 'UG',
  'Ouzbékistan': 'UZ',
  'Pakistan': 'PK',
  'Panama': 'PA',
  'Papouasie-Nouvelle-Guinée': 'PG',
  'Paraguay': 'PY',
  'Pays-Bas': 'NL',
  'Pérou': 'PE',
  'Philippines': 'PH',
  'Pologne': 'PL',
  'Portugal': 'PT',
  'Qatar': 'QA',
  'Roumanie': 'RO',
  'Royaume-Uni': 'GB',
  'Russie': 'RU',
  'Rwanda': 'RW',
  'Sainte-Lucie': 'LC',
  'Saint-Marin': 'SM',
  'Sao Tomé-et-Principe': 'ST',
  'Sénégal': 'SN',
  'Serbie': 'RS',
  'Seychelles': 'SC',
  'Sierra Leone': 'SL',
  'Singapour': 'SG',
  'Slovaquie': 'SK',
  'Slovénie': 'SI',
  'Somalie': 'SO',
  'Soudan': 'SD',
  'Soudan du Sud': 'SS',
  'Suède': 'SE',
  'Suisse': 'CH',
  'Suriname': 'SR',
  'Syrie': 'SY',
  'Tadjikistan': 'TJ',
  'Tanzanie': 'TZ',
  'Tchad': 'TD',
  'Tchéquie': 'CZ',
  'Thaïlande': 'TH',
  'Timor oriental': 'TL',
  'Togo': 'TG',
  'Tonga': 'TO',
  'Trinité-et-Tobago': 'TT',
  'Tunisie': 'TN',
  'Turkménistan': 'TM',
  'Turquie': 'TR',
  'Ukraine': 'UA',
  'Uruguay': 'UY',
  'Vanuatu': 'VU',
  'Venezuela': 'VE',
  'Viêt Nam': 'VN',
  'Yémen': 'YE',
  'Zambie': 'ZM',
  'Zimbabwe': 'ZW'
};



export const getCountryCode = (countryName) => {
  return countryMapping[countryName] || countryName;
};


export const getCountryName = (countryCode) => {
  const entry = Object.entries(countryMapping).find(([name, code]) => code === countryCode);
  return entry ? entry[0] : countryCode;
}; 